---
# tasks file for filebeat

- name: Subscribe to required channels
  import_role:
    name: spacewalk-client
    tasks_from: channel.yml
  vars:
    channels: '{{ filebeat_rhn_channels }}'

- name: Install required packages
  yum:
    name: 'filebeat'
    state: installed
  notify: update aide
  tags:
    - install

- name: Copy Filebeat configuration.
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart filebeat
    - update aide

- name: Ensure services
  service:
    name: filebeat
    state: started
    enabled: true
  notify: update aide
  tags:
    - service


